# Generated by Django 6.0.4 on 2026-04-11 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(default='2024-2025', max_length=20)),
                ('home_played', models.IntegerField(default=0)),
                ('home_wins', models.IntegerField(default=0)),
                ('home_losses', models.IntegerField(default=0)),
                ('away_played', models.IntegerField(default=0)),
                ('away_wins', models.IntegerField(default=0)),
                ('away_losses', models.IntegerField(default=0)),
                ('attack_efficiency_made', models.IntegerField(default=0)),
                ('attack_efficiency_total', models.IntegerField(default=0)),
                ('block_success_rate', models.IntegerField(default=0)),
                ('serve_efficiency_made', models.IntegerField(default=0)),
                ('serve_efficiency_total', models.IntegerField(default=0)),
                ('reception_accuracy_made', models.IntegerField(default=0)),
                ('reception_accuracy_total', models.IntegerField(default=0)),
                ('side_out_made', models.IntegerField(default=0)),
                ('side_out_total', models.IntegerField(default=0)),
                ('comeback_rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opponent', models.CharField(max_length=100)),
                ('kills', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
                ('aces', models.IntegerField(default=0)),
                ('mvp', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='players.player')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
