# Generated by Django 4.2.30 on 2026-04-21 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancerecord_official_status_and_response'),
        ('statistics_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_score', models.PositiveIntegerField(default=0)),
                ('opponent_score', models.PositiveIntegerField(default=0)),
                ('sets_won', models.PositiveSmallIntegerField(default=0)),
                ('sets_lost', models.PositiveSmallIntegerField(default=0)),
                ('kills', models.PositiveIntegerField(default=0)),
                ('blocks', models.PositiveIntegerField(default=0)),
                ('aces', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_stat', to='attendance.match')),
            ],
            options={
                'ordering': ['-match__date'],
            },
        ),
    ]
