# Generated by Django 4.2.30 on 2026-04-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Player'), ('coach', 'Coach')], default='student', max_length=10),
        ),
    ]
