# Generated by Django 6.0.4 on 2026-04-11 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('jersey_number', models.PositiveSmallIntegerField()),
                ('position', models.CharField(choices=[('OH', 'Outside Hitter'), ('OPP', 'Opposite Hitter'), ('S', 'Setter'), ('MB', 'Middle Blocker'), ('L', 'Libero'), ('DS', 'Defensive Specialist')], max_length=5)),
                ('player_type', models.CharField(choices=[('Starting', 'Starting'), ('Substitute', 'Substitute')], default='Starting', max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('points', models.PositiveIntegerField(default=0)),
                ('kills', models.PositiveIntegerField(default=0)),
                ('blocks', models.PositiveIntegerField(default=0)),
                ('aces', models.PositiveIntegerField(default=0)),
                ('digs', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('attack_pct', models.PositiveSmallIntegerField(default=0)),
                ('perfect_recv_pct', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['player_type', 'jersey_number'],
            },
        ),
    ]
