# Generated by Django 4.2.30 on 2026-04-12 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['player_type', 'jersey_number', 'name']},
        ),
    ]
