# Generated by Django 4.2.30 on 2026-04-12 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_notification_recipients(apps, schema_editor):
    Notification = apps.get_model('notifications', 'Notification')
    NotificationRecipient = apps.get_model('notifications', 'NotificationRecipient')
    CustomUser = apps.get_model('accounts', 'CustomUser')

    user_ids = list(CustomUser.objects.filter(is_active=True).values_list('id', flat=True))
    recipients = []
    for notification in Notification.objects.all():
        is_read = notification.status == 'Read'
        for user_id in user_ids:
            recipients.append(
                NotificationRecipient(
                    notification_id=notification.id,
                    user_id=user_id,
                    is_read=is_read,
                    read_at=notification.created_at if is_read else None,
                )
            )
    NotificationRecipient.objects.bulk_create(recipients, ignore_conflicts=True)


def remove_notification_recipients(apps, schema_editor):
    NotificationRecipient = apps.get_model('notifications', 'NotificationRecipient')
    NotificationRecipient.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_read', '-notification__created_at'],
                'unique_together': {('notification', 'user')},
            },
        ),
        migrations.RunPython(create_notification_recipients, remove_notification_recipients),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
    ]
