# Generated by Django 6.0.4 on 2026-04-11 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('match_type', models.CharField(choices=[('Match', 'Match'), ('Practice', 'Practice')], default='Match', max_length=20)),
                ('date', models.DateTimeField()),
                ('duration_hours', models.PositiveSmallIntegerField(default=2)),
                ('location', models.CharField(default='Charles Hostler', max_length=200)),
                ('confirmation_closes', models.DateTimeField(blank=True, null=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Attending', 'Attending'), ('Not Attending', 'Not Attending'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.match')),
            ],
            options={
                'unique_together': {('match', 'player')},
            },
        ),
    ]
