# Generated by Django 4.2.30 on 2026-04-12 10:46

from django.db import migrations, models
from django.utils import timezone


def populate_match_status(apps, schema_editor):
    Match = apps.get_model('attendance', 'Match')
    now = timezone.now()
    for match in Match.objects.all():
        match.status = 'Completed' if match.date < now else 'Upcoming'
        match.save(update_fields=['status'])


def reset_match_status(apps, schema_editor):
    Match = apps.get_model('attendance', 'Match')
    Match.objects.all().update(status='Upcoming')


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Postponed', 'Postponed'), ('Problem', 'Problem / Needs Attention')], default='Upcoming', max_length=20),
        ),
        migrations.RunPython(populate_match_status, reset_match_status),
    ]
