# Generated by Django 4.2.30 on 2026-04-25 12:17

from django.db import migrations, models


def move_problem_matches_to_postponed(apps, schema_editor):
    Match = apps.get_model("attendance", "Match")
    Match.objects.filter(status="Problem").update(status="Postponed")


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancerecord_official_status_and_response'),
    ]

    operations = [
        migrations.RunPython(
            move_problem_matches_to_postponed,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Postponed', 'Postponed')], default='Upcoming', max_length=20),
        ),
    ]
